# Generated by Django 3.1.1 on 2020-09-14 04:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('architectApps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company_details',
            name='Img',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='images/'),
            preserve_default=False,
        ),
    ]
