# Generated by Django 3.1.1 on 2020-09-14 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('architectApps', '0002_company_details_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company_details',
            old_name='Img',
            new_name='cover_pic',
        ),
    ]
