# Generated by Django 3.1.1 on 2020-09-14 06:42

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('architectApps', '0005_auto_20200914_0626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company_details',
            name='company_description',
            field=tinymce.models.HTMLField(blank=True, help_text='Enter Company Descriptions'),
        ),
        migrations.AlterField(
            model_name='company_details',
            name='company_moto',
            field=models.CharField(help_text='Enter Company Moto', max_length=200),
        ),
        migrations.AlterField(
            model_name='company_details',
            name='company_name',
            field=models.CharField(help_text='Enter Company Name', max_length=200),
        ),
        migrations.AlterField(
            model_name='company_details',
            name='cover_pic',
            field=models.ImageField(help_text='Enter Company Cover Pic(max-height:250px)', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='company_details',
            name='logo_pic',
            field=models.ImageField(help_text='Enter Company Logo Pic(height:220px,width:220px)', upload_to='images/'),
        ),
    ]
