# Generated by Django 3.1.1 on 2020-09-14 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('architectApps', '0007_academic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='academic',
            old_name='sproject_cover_pic',
            new_name='project_cover_pic',
        ),
    ]
